import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { allShortestPathsFrom } from '../src/lib/pathfinding'

type PathEntry = { steps: number; moves: number[] } | null

function precomputeAllPaths(): PathEntry[] {
  return allShortestPathsFrom(0).map((p) => (p === null ? null : { steps: p.steps, moves: p.moves }))
}

function renderTs(paths: PathEntry[]): string {
  return `/* eslint-disable */
// This file is auto-generated by scripts/precompute-paths.ts
// Run: npm run precompute

export type PathEntry = { steps: number; moves: number[] } | null

export const PATHS: PathEntry[] = ${JSON.stringify(paths)} as const
`
}

const outputFile = resolve(process.cwd(), 'src', 'generated', 'paths.ts')
const paths = precomputeAllPaths()
mkdirSync(resolve(process.cwd(), 'src', 'generated'), { recursive: true })
writeFileSync(outputFile, renderTs(paths), 'utf8')
console.log(`Generated ${outputFile}`)
